# Generated by Django 5.0.1 on 2024-01-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_categories_article_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
